### ISSUE TITLE
ICS Lens Tables remain empty

### ISSUE THREAD

**Issue by tijldeneut** [CyberLens/Discovery#22]
After importing and replaying a pcap which holds several Modbus and Ethernet/IP sessions, we notice that the data tables are filled correctly. But all ICS Lens Tables remain at "0 records". 

Ubuntu Server x64 20.04 fully updated with Cyberlens v1.4.2

The PCAP filesize is 177MB.

**Comment by Or3stis** [comment]
This refers to another tool. We will close this issue.
